[build]
  publish = "frontend"

# Redirige la raíz al login para tener una página principal
[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200

# Proxy para el backend
[[redirects]]
  from = "/api/*"
  to = "https://backend-5wh5.onrender.com/api/:splat"
  status = 200
  force = true

# Proxy para archivos subidos (imágenes de productos)
[[redirects]]
  from = "/uploads/*"
  to = "https://backend-5wh5.onrender.com/uploads/:splat"
  status = 200
  force = true